In [1]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import plotly.graph_objs as go
import re
from jupyter_dash import JupyterDash  # Use JupyterDash instead of dash.Dash
import dash
from dash import html
import dash_cytoscape as cyto

In [2]:
file_path = 'D:\\test\\ExcelManualCleaning.csv'
df = pd.read_csv(file_path)

In [3]:
df.head()

,s_no,acknowledgement_no,transaction_id,layer,to_account_no,action_taken_by_bank_wallet_pgpa_merchant_insurance,bank_wallet_pgpa_merchant__insurance,from_account_no,ifsc_code,cheque_no,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,1,`30209240022092,`PUNBR52024090612314232,2,`8830210000008880,Money Transfer to,Federal Bank,`24610100000643,FDRL0001010,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,`30209240022092,`PUNBR52024090612314232,2,`8830210000008880,Money Transfer to,Canara Bank,`110196345628,CNRB0004785,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,`30209240022092,`PUNBR52024090612314232,2,`8830210000008880,Money Transfer to,Canara Bank,`110189607716,CNRB0004785,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,`30209240022092,`PUNBR52024090612314232,2,`8830210000008880,Money Transfer to,South Indian Bank,`179053000017033,SIBL0000848,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,`30209240022092,`PUNBR52024090612314232,2,`8830210000008880,Money Transfer to,Bandhan Bank,`20200057515505,BDBL0001815,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df['amount']=df['amount'].astype(int)

In [5]:
df['layer'] = df['layer'].astype(int)

In [6]:
df = df.drop(['s_no'],axis=1)
# Remove text within square brackets
df['to_account_no'] = df['to_account_no'].str.replace(r'\s*\[.*?\]', '', regex=True)

In [7]:
# Define the columns to clean
columns_to_clean = [
    'acknowledgement_no', 'transaction_id', 'layer',
    'from_account_no', 'utr_number', 'amount','to_account_no'
]

# Function to clean data in a column
def clean_column_data(series):
    # Remove special characters and trim spaces
    series = series.apply(lambda x: re.sub(r'[^\w\s]', '', str(x)).strip() if pd.notna(x) else x)
    return series

# Apply the cleaning function to each specified column
for col in columns_to_clean:
    if col in df.columns:
        df[col] = clean_column_data(df[col])

# Display the cleaned data to verify
print(df[columns_to_clean].head())

  acknowledgement_no          transaction_id layer  from_account_no  \
0     30209240022092  PUNBR52024090612314232     2   24610100000643
1     30209240022092  PUNBR52024090612314232     2     110196345628
2     30209240022092  PUNBR52024090612314232     2     110189607716
3     30209240022092  PUNBR52024090612314232     2  179053000017033
4     30209240022092  PUNBR52024090612314232     2   20200057515505

               utr_number  amount     to_account_no
0  DBSSR52024090605165954  270000  8830210000008880
1  DBSSR52024090605165914  200000  8830210000008880
2             CNRB0004785  399999  8830210000008880
3  DBSSR52024090605165915  371900  8830210000008880
4  DBSSR52024090605165951  290178  8830210000008880

In [8]:
df['unique_id'] = pd.Series(range(1, len(df) + 1))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 39 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   acknowledgement_no                                   156 non-null    object
 1   transaction_id                                       156 non-null    object
 2   layer                                                156 non-null    object
 3   to_account_no                                        156 non-null    object
 4   action_taken_by_bank_wallet_pgpa_merchant_insurance  156 non-null    object
 5   bank_wallet_pgpa_merchant__insurance                 156 non-null    object
 6   from_account_no                                      156 non-null    object
 7   ifsc_code                                            96 non-null     object
 8   cheque_no                                            156 non-null    int64
 9   mid                                                  5 non-null      float64
 10  tid                                                  5 non-null      object
 11  approval_code                                        5 non-null      float64
 12  merchant_name                                        5 non-null      object
 13  transaction_date                                     156 non-null    object
 14  utr_number                                           108 non-null    object
 15  amount                                               156 non-null    object
 16  reference_no                                         0 non-null      float64
 17  remarks                                              118 non-null    object
 18  date_of_action                                       156 non-null    object
 19  action_taken_by_bank                                 156 non-null    object
 20  action_taken_name                                    156 non-null    object
 21  action_taken_by_email                                156 non-null    object
 22  branch_location                                      21 non-null     object
 23  branch_manager_name__contact_details                 8 non-null      object
 24  unnamed_25                                           3 non-null      object
 25  unnamed_26                                           1 non-null      object
 26  Unnamed: 27                                          0 non-null      float64
 27  Unnamed: 28                                          0 non-null      float64
 28  Unnamed: 29                                          0 non-null      float64
 29  Unnamed: 30                                          0 non-null      float64
 30  Unnamed: 31                                          0 non-null      float64
 31  Unnamed: 32                                          0 non-null      float64
 32  Unnamed: 33                                          0 non-null      float64
 33  Unnamed: 34                                          0 non-null      float64
 34  Unnamed: 35                                          0 non-null      float64
 35  Unnamed: 36                                          0 non-null      float64
 36  Unnamed: 37                                          0 non-null      float64
 37  Unnamed: 38                                          4 non-null      object
 38  unique_id                                            156 non-null    int64
dtypes: float64(14), int64(2), object(23)
memory usage: 47.7+ KB

In [9]:
df['layer'] = pd.to_numeric(df['layer'], errors='coerce')
print(df['layer'].unique())

[2 3 1 4 5 6 7]

In [10]:
layers = df.groupby('layer')
layer1 = layers.get_group(1)
layer1

,acknowledgement_no,transaction_id,layer,to_account_no,action_taken_by_bank_wallet_pgpa_merchant_insurance,bank_wallet_pgpa_merchant__insurance,from_account_no,ifsc_code,cheque_no,mid,...,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,unique_id
21,30209240022092,SBINR52024090646591003,1,8830210000008880,Transaction put on hold,DBS Bank,1146110010053650,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
34,30209240022092,PUNBR52024090612314232,1,10832030036580,Money Transfer to,DBS Bank,8830210000008880,DBSS0IN0830,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35
38,30209240022092,PUNBR52024090612314232,1,8830210000008880,Other,DBS Bank,,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39
39,30209240022092,SBINR52024090646591003,1,10047593897,Money Transfer to,DBS Bank,8830210000008880,DBSS0IN0830,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40
40,30209240022092,965562,1,10047593897,Money Transfer to,State Bank of India,43017388358,SBIN0001464,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41
41,30209240022092,965563,1,10047593897,Money Transfer to,State Bank of India,43280321955,SBIN0011519,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42
42,30209240022092,965562,1,43017388358,Other,State Bank of India,,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43
43,30209240022092,965563,1,43280321955,Other,State Bank of India,,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44
44,30209240022092,10047593897,1,43017388358,Other,State Bank of India,,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45
45,30209240022092,10047593897,1,43280321955,Other,State Bank of India,,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46
52,30209240022092,SBINR52024090646591003,1,8830210000008880,Other,DBS Bank,,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53

In [86]:
# Assuming df contains your data
layers = df.groupby('layer')
for layer_num, layer_data in layers:
    # Get distinct account numbers
    print(layer_data)
    distinct_accounts = layer_data['from_account_no'].unique()
    print(distinct_accounts)

   acknowledgement_no          transaction_id  layer     to_account_no  \
21     30209240022092  SBINR52024090646591003      1  8830210000008880
34     30209240022092  PUNBR52024090612314232      1    10832030036580
38     30209240022092  PUNBR52024090612314232      1  8830210000008880
39     30209240022092  SBINR52024090646591003      1       10047593897
40     30209240022092                  965562      1       10047593897
41     30209240022092                  965563      1       10047593897
42     30209240022092                  965562      1       43017388358
43     30209240022092                  965563      1       43280321955
44     30209240022092             10047593897      1       43017388358
45     30209240022092             10047593897      1       43280321955
52     30209240022092  SBINR52024090646591003      1  8830210000008880

   action_taken_by_bank_wallet_pgpa_merchant_insurance  \
21                            Transaction put on hold
34                                  Money Transfer to
38                                              Other
39                                  Money Transfer to
40                                  Money Transfer to
41                                  Money Transfer to
42                                              Other
43                                              Other
44                                              Other
45                                              Other
52                                              Other

   bank_wallet_pgpa_merchant__insurance   from_account_no    ifsc_code  \
21                            DBS Bank   1146110010053650          NaN
34                            DBS Bank   8830210000008880  DBSS0IN0830
38                            DBS Bank                NaN          NaN
39                            DBS Bank   8830210000008880  DBSS0IN0830
40                  State Bank of India       43017388358  SBIN0001464
41                  State Bank of India       43280321955  SBIN0011519
42                  State Bank of India               NaN          NaN
43                  State Bank of India               NaN          NaN
44                  State Bank of India               NaN          NaN
45                  State Bank of India               NaN          NaN
52                            DBS Bank                NaN          NaN

    cheque_no  mid  ...                                            remarks  \
21          0  NaN  ...                           Transaction put on hold.
34          0  NaN  ...  NRTGS/PUNBR52024090612314232/CRAVY MEALES ENTE...
38          0  NaN  ...                              Duplicate transaction
39          0  NaN  ...                      Transaction amount 2799952.80
40          0  NaN  ...                                                NaN
41          0  NaN  ...                                                NaN
42          0  NaN  ...  Account does not have sufficient balance. However
43          0  NaN  ...  Account does not have sufficient balance. However
44          0  NaN  ...    Repeated transaction. Action already initiated.
45          0  NaN  ...    Repeated transaction. Action already initiated.
52          0  NaN  ...                                  Already actioned.

                                   date_of_action  \
21                               22-09-2024 17:59
34                               22-09-2024 18:06
38                               22-09-2024 18:10
39                               22-09-2024 18:13
40                               22-09-2024 18:18
41                               22-09-2024 18:19
42   Hold Kept for the disputed amount Rs.1100000
43   Hold Kept for the disputed amount Rs.1200000
44                               22-09-2024 18:20
45                               22-09-2024 18:20
52                               22-09-2024 18:30

                                 action_taken_by_bank    action_taken_name  \
21            DBS Bank (Including Lakshmi Vilas Bank)     Akanksha Bhagade
34  Punjab National Bank (including Oriental Bank ...          Rahul Singh
38            DBS Bank (Including Lakshmi Vilas Bank)          Ajeet Kumar
39                                State Bank of India      S V Vinod Kumar
40                                State Bank of India      S V Vinod Kumar
41                                State Bank of India      S V Vinod Kumar
42                                   22-09-2024 18:19  State Bank of India
43                                   22-09-2024 18:19  State Bank of India
44                                State Bank of India      S V Vinod Kumar
45                                State Bank of India      S V Vinod Kumar
52            DBS Bank (Including Lakshmi Vilas Bank)     Akanksha Bhagade

       action_taken_by_email           branch_location  \
21   akankshabhagade@dbs.com                       NaN
34      nccrpc.i4c@pnb.co.in                       NaN
38        ajeetkumar@dbs.com                       NaN
39  agmsrvl.lhoand@sbi.co.in                       NaN
40  agmsrvl.lhoand@sbi.co.in                       NaN
41  agmsrvl.lhoand@sbi.co.in                       NaN
42           S V Vinod Kumar  agmsrvl.lhoand@sbi.co.in
43           S V Vinod Kumar  agmsrvl.lhoand@sbi.co.in
44  agmsrvl.lhoand@sbi.co.in                       NaN
45  agmsrvl.lhoand@sbi.co.in                       NaN
52   akankshabhagade@dbs.com                       NaN

    branch_manager_name__contact_details unnamed_25 unnamed_26 unique_id
21                                   NaN        NaN        NaN        22
34                                   NaN        NaN        NaN        35
38                                   NaN        NaN        NaN        39
39                                   NaN        NaN        NaN        40
40                                   NaN        NaN        NaN        41
41                                   NaN        NaN        NaN        42
42                                   NaN        NaN        NaN        43
43                                   NaN        NaN        NaN        44
44                                   NaN        NaN        NaN        45
45                                   NaN        NaN        NaN        46
52                                   NaN        NaN        NaN        53

[11 rows x 27 columns]
['1146110010053650' '8830210000008880' nan '43017388358' '43280321955']
    acknowledgement_no          transaction_id  layer     to_account_no  \
0       30209240022092  PUNBR52024090612314232      2  8830210000008880
1       30209240022092  PUNBR52024090612314232      2  8830210000008880
2       30209240022092  PUNBR52024090612314232      2  8830210000008880
3       30209240022092  PUNBR52024090612314232      2  8830210000008880
4       30209240022092  PUNBR52024090612314232      2  8830210000008880
5       30209240022092  PUNBR52024090612314232      2  8830210000008880
6       30209240022092  PUNBR52024090612314232      2  8830210000008880
7       30209240022092  PUNBR52024090612314232      2  8830210000008880
8       30209240022092  PUNBR52024090612314232      2  8830210000008880
9       30209240022092  PUNBR52024090612314232      2  8830210000008880
10      30209240022092  PUNBR52024090612314232      2  8830210000008880
11      30209240022092  PUNBR52024090612314232      2  8830210000008880
12      30209240022092  PUNBR52024090612314232      2  8830210000008880
13      30209240022092  DBSSR52024090605165958      2  2401216960825130
22      30209240022092  SBINR52024090646591003      2  8830210000008880
23      30209240022092  SBINR52024090646591003      2  8830210000008880
24      30209240022092  SBINR52024090646591003      2  8830210000008880
25      30209240022092  SBINR52024090646591003      2  8830210000008880
26      30209240022092  SBINR52024090646591003      2  8830210000008880
30      30209240022092  DBSSR52024090605165916      2  2401227259431240
46      30209240022092                  965562      2       43017388358
47      30209240022092                  965562      2       43017388358
48      30209240022092                  965562      2       43017388358
49      30209240022092                  965562      2       43017388358
50      30209240022092                  965562      2       43017388358
51      30209240022092                  965562      2       43017388358
53      30209240022092                  965563      2       43280321955
54      30209240022092                  965563      2       43280321955
55      30209240022092                  965563      2       43280321955
56      30209240022092                  965563      2       43280321955
63      30209240022092  SBINR12024091047262739      2      110134809783
65      30209240022092  SBINR12024091047262739      2      110134809783
68      30209240022092        SBIN124254411029      2      110170638899
79      30209240022092  SBINR12024091247810781      2    22751400002853
85      30209240022092  DBSSR52024090605165918      2    21360100147753
86      30209240022092  DBSSR52024090605165954      2    24610100000643
88      30209240022092  DBSSR52024090605165954      2    24610100000643
89      30209240022092  DBSSR52024090605165954      2    24610100000643
91      30209240022092  DBSSR52024090605166673      2    24610100005204
92      30209240022092  DBSSR52024090605166673      2    24610100005204
93      30209240022092  DBSSR52024090605166673      2    24610100005204
95      30209240022092  DBSSR52024090605166706      2    18670100063718
97      30209240022092  DBSSR52024090605166706      2    18670100063718
101     30209240022092  SBINR12024091247810785      2   924010041487963
117     30209240022092  DBSSR52024090605165917      2  1607104000080370
118     30209240022092  DBSSR52024090605165917      2  1607104000080370
132     30209240022092  DBSSR52024090605165952      2    50100741696880
133     30209240022092  DBSSR52024090605165952      2    50100741696880
144     30209240022092  PUNBR52024090612314232      2  8830210000008880
145     30209240022092  DBSSR52024090605165952      2    50100741696880
146     30209240022092  PUNBR52024090612314232      2  8830210000008880

    action_taken_by_bank_wallet_pgpa_merchant_insurance  \
0                                    Money Transfer to
1                                    Money Transfer to
2                                    Money Transfer to
3                                    Money Transfer to
4                                    Money Transfer to
5                                    Money Transfer to
6                                    Money Transfer to
7                                    Money Transfer to
8                                    Money Transfer to
9                                    Money Transfer to
10                                   Money Transfer to
11                                   Money Transfer to
12                                   Money Transfer to
13                      Cash Withdrawal through Cheque
22                                   Money Transfer to
23                                   Money Transfer to
24                                   Money Transfer to
25                                   Money Transfer to
26                                   Money Transfer to
30                      Cash Withdrawal through Cheque
46                                   Money Transfer to
47                                   Money Transfer to
48                                   Money Transfer to
49                                   Money Transfer to
50                                   Money Transfer to
51                                   Money Transfer to
53                                   Money Transfer to
54                                   Money Transfer to
55                                   Money Transfer to
56                                   Money Transfer to
63                              Withdrawal through ATM
65                              Withdrawal through ATM
68                              Withdrawal through ATM
79                                               Other
85                              Withdrawal through ATM
86                              Withdrawal through ATM
88                              Withdrawal through ATM
89                                               Other
91                              Withdrawal through ATM
92                              Withdrawal through ATM
93                                               Other
95                              Withdrawal through ATM
97                                               Other
101                             Withdrawal through ATM
117                             Withdrawal through ATM
118                             Withdrawal through ATM
132                             Withdrawal through POS
133                             Withdrawal through POS
144                                  Money Transfer to
145                             Withdrawal through POS
146                                  Money Transfer to

    bank_wallet_pgpa_merchant__insurance   from_account_no    ifsc_code  \
0                           Federal Bank    24610100000643  FDRL0001010
1                           Canara Bank       110196345628  CNRB0004785
2                           Canara Bank       110189607716  CNRB0004785
3                      South Indian Bank   179053000017033  SIBL0000848
4                           Bandhan Bank    20200057515505  BDBL0001815
5                           Bandhan Bank    20200059779220  BDBL0001592
6                                AU Bank  2401216960825130  AUBL0002556
7                              IDBI Bank  1607104000080370  IBKL0001648
8                           Federal Bank    21360100147753  FDRL0001010
9                                AU Bank  2401227259431240  AUBL0002556
10                          Bandhan Bank    20200059117762  BDBL0001815
11                   Bank of Maharashtra       60496115000  MAHB0000005
12                   Bank of Maharashtra       60501402002  MAHB0000005
13                               AU Bank  2401216960825130  AUBL0002163
22        Ujjivan Small Finance Bank Ltd  1146110010053650  UJVN0001146
23                          Bandhan Bank    20200050694941  BDBL0001592
24                          Federal Bank    18670100063718  FDRL0001759
25                          Federal Bank    24610100005204  FDRL0001759
26                            ICICI Bank       79801513015  ICIC0000798
30                               AU Bank  2401227259431240  AUBL0002272
46                          Canara Bank       110170638899  CNRB0007447
47                          Bandhan Bank    20200060776541  BDBL0001557
48                          Bandhan Bank    20200060503423  BDBL0001797
49    Utkarsh Small Finance Bank Limited  1564019694617840  UTKS0001564
50                          Canara Bank       110134809783  CNRB0006641
51                          Bandhan Bank    20200060530420  BDBL0001480
53                          Federal Bank     1001014000220  FDRL0SPCB01
54                              Yes Bank    22751400002853  YESB0000227
55                          Bandhan Bank    20200058727202  BDBL0001518
56                             Axis Bank   924010041487963  UTIB0002882
63                          Canara Bank                NaN          NaN
65                          Canara Bank                NaN          NaN
68                          Canara Bank                NaN          NaN
79                              Yes Bank               NaN          NaN
85                          Federal Bank   922010019482631          NaN
86                          Federal Bank          WPGTID01          NaN
88                          Federal Bank          WPGTID01          NaN
89                          Federal Bank               NaN          NaN
91                          Federal Bank          44963344          NaN
92                          Federal Bank          44963344          NaN
93                          Federal Bank               NaN          NaN
95                          Federal Bank          WPGTID01          NaN
97                          Federal Bank               NaN          NaN
101                            Axis Bank    50100277170880          NaN
117                            IDBI Bank               NaN          NaN
118                            IDBI Bank   131451400002071          NaN
132                            HDFC Bank               NaN          NaN
133                            HDFC Bank               NaN          NaN
144                            HDFC Bank    50100741696880  HDFC0000365
145                            HDFC Bank               NaN          NaN
146   Utkarsh Small Finance Bank Limited  1564017023043730  UTKS0001564

     cheque_no           mid  ...  \
0            0           NaN  ...
1            0           NaN  ...
2            0           NaN  ...
3            0           NaN  ...
4            0           NaN  ...
5            0           NaN  ...
6            0           NaN  ...
7            0           NaN  ...
8            0           NaN  ...
9            0           NaN  ...
10           0           NaN  ...
11           0           NaN  ...
12           0           NaN  ...
13           4           NaN  ...
22           0           NaN  ...
23           0           NaN  ...
24           0           NaN  ...
25           0           NaN  ...
26           0           NaN  ...
30          13           NaN  ...
46           0           NaN  ...
47           0           NaN  ...
48           0           NaN  ...
49           0           NaN  ...
50           0           NaN  ...
51           0           NaN  ...
53           0           NaN  ...
54           0           NaN  ...
55           0           NaN  ...
56           0           NaN  ...
63           0           NaN  ...
65           0           NaN  ...
68           0           NaN  ...
79           0           NaN  ...
85           0           NaN  ...
86           0           NaN  ...
88           0           NaN  ...
89           0           NaN  ...
91           0           NaN  ...
92           0           NaN  ...
93           0           NaN  ...
95           0           NaN  ...
97           0           NaN  ...
101          0           NaN  ...
117          0           NaN  ...
118          0           NaN  ...
132          0  1.144000e+14  ...
133          0  2.006010e+11  ...
144          0           NaN  ...
145          0  2.006010e+11  ...
146          0           NaN  ...

                                               remarks  \
0                        RTGS 0830OI4005165954 BHUPESH
1                      RTGS 0830OI4005165914 JUNJA RAM
2                       RTGS 0830OI4005165956 AKBARALI
3           RTGS 0830OI4005165915 SHAIKH MOHAMMEDSAJID
4                         RTGS 0830OI4005165951 KISHOR
5                      RTGS 0830OI4005165959 ACHALARAM
6              RTGS 0830OI4005165958 ASHOK KUMAR MEENA
7                     RTGS 0830OI4005165917 RAVI KUMAR
8                       RTGS 0830OI4005165918 ANAM C P
9                     RTGS 0830OI4005165916 ARBAJ KHAN
10                RTGS 0830OI4005165913 VIRENDRA KUMAR
11         RTGS 0830OI4005165955 MR MUSHTAK KHAN KARIM
12         RTGS 0830OI4005165953 SEJAL VASUDEV MESHRAM
13                                         DA 245000/-
22       RTGS 0830OI4005166760 MUHAMMED SHYAM SHAJAHAN
23                      RTGS 0830OI4005166704 RAMKUMAR
24                        RTGS 0830OI4005166706 BIJITH
25                     RTGS 0830OI4005166673 AKBAR ALI
26                  RTGS 0830OI4005166705 CHETAN KUMAR
30   Necessary steps have been applied on the said ...
46                                                 NaN
47                                                 NaN
48                                                 NaN
49                                                 NaN
50                                                 NaN

In [11]:
def format_amount_indian(amount):
    # Convert the amount to a string and remove any existing commas
    amount_str = str(amount).replace(',', '')
    
    # Check if the number has more than 3 digits
    if len(amount_str) > 3:
        # Get the last 3 digits
        last_three = amount_str[-3:]
        # Get the remaining digits
        remaining = amount_str[:-3]
        # Reverse the remaining digits for easier grouping
        remaining_reversed = remaining[::-1]
        # Group digits in thousands (group of 2 after the first group of 3)
        grouped = [remaining_reversed[i:i+2] for i in range(0, len(remaining_reversed), 2)]
        # Reverse and join the grouped digits with commas
        formatted_remaining = ','.join(grouped[::-1]).lstrip('0')  # lstrip removes any leading zeroes
        # Concatenate the formatted remaining part with the last three digits
        formatted_amount = f'{formatted_remaining},{last_three}' if formatted_remaining else last_three
    else:
        # For amounts less than or equal to 999, no formatting is needed
        formatted_amount = amount_str

    return formatted_amount

In [12]:
ackno = df['acknowledgement_no'].unique()
ackname = 'Transaction Graph For (Ack No): ' + str(ackno)
ackname

"Transaction Graph For (Ack No): ['30209240022092']"

In [13]:
layer1_records = df[(df['layer'] == 1) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
layer1_nodes = layer1_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date','ifsc_code', 'amount', 'remarks']]

layer1_nodes

,from_account_no,to_account_no,transaction_id,transaction_date,ifsc_code,amount,remarks
34,8830210000008880,10832030036580,PUNBR52024090612314232,06-09-2024 11:00,DBSS0IN0830,4100000,NRTGS/PUNBR52024090612314232/CRAVY MEALES ENTE...
39,8830210000008880,10047593897,SBINR52024090646591003,06-09-2024 16:49,DBSS0IN0830,2799952,Transaction amount 2799952.80
40,43017388358,10047593897,965562,10-09-2024 13:02,SBIN0001464,1100000,NaN
41,43280321955,10047593897,965563,12-09-2024 00:00,SBIN0011519,1200000,NaN

In [14]:
from graphviz import Digraph

# Create a directed graph using Graphviz with hierarchical layout
dot = Digraph()

# Set the graph layout to be hierarchical (left-right) and use L-shaped edges
dot.attr(rankdir='LR', splines='ortho')

# Get the distinct unique layers from the dataset
layers = sorted(df['layer'].unique())

# Initialize the previous layer nodes (starting with an empty set)
previous_layer_nodes = None

# Set to track already added edges to avoid duplicates
added_edges = set()

# Loop through each distinct layer in the dataset
for idx, layer in enumerate(layers):
    
    # Step 1: For the first layer, apply Money Transfer filter
    if idx == 0:
        layer_records = df[(df['layer'] == layer) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
    # Step 2: For other layers, only filter by layer
    else:
        layer_records = df[df['layer'] == layer]

    # Select relevant columns from the filtered dataset
    layer_nodes = layer_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date', 'ifsc_code', 'amount', 'remarks', 'action_taken_by_bank_wallet_pgpa_merchant_insurance']]
    
    # Add nodes for the current layer (from_account_no as nodes, with rectangular shape)
    for _, row in layer_nodes.iterrows():
        # Default color is black
        node_color = 'black'
        
        # Change node color if 'WITHDRAWAL' is in action_taken_by_bank_wallet_pgpa_merchant_insurance
        if 'WITHDRAWAL' in row['action_taken_by_bank_wallet_pgpa_merchant_insurance'].upper():
            node_color = '#0000ff'  # Blue color for withdrawal
            
        # Change node color if 'ON HOLD' is in action_taken_by_bank_wallet_pgpa_merchant_insurance
        elif 'ON HOLD' in row['action_taken_by_bank_wallet_pgpa_merchant_insurance'].upper():
            node_color = '#ff0000'  # Red color for on hold
        
        # Add node with the specific color and rectangular shape
        dot.node(
            str(row['from_account_no']), 
            label=f"Acc: {row['from_account_no']}\nTransID: {row['transaction_id']}\nIFSC Code: {row['ifsc_code']}\nAmount: {format_amount_indian(row['amount'])}", 
            shape='box',
            color=node_color
        )

    # If this is not the first layer, add edges between the previous layer and the current one
    if previous_layer_nodes is not None:
        # Add edges based on "to_account_no" in the current layer matching "from_account_no" in the previous layer
        for _, row in layer_nodes.iterrows():
            matching_previous_layer_nodes = previous_layer_nodes[previous_layer_nodes['from_account_no'] == row['to_account_no']]
            
            for _, prev_row in matching_previous_layer_nodes.iterrows():
                # Create an identifier for the edge to check for duplicates
                edge = (str(prev_row['from_account_no']), str(row['from_account_no']))
                
                # Add edge if it hasn't been added yet
                if edge not in added_edges:
                    # Add L-shaped edge from the previous layer's from_account_no to the current layer's from_account_no
                    dot.edge(str(prev_row['from_account_no']), str(row['from_account_no']), label=f"Transfer on {row['transaction_date']}")
                    added_edges.add(edge)  # Track the added edge

    # Set the current layer as the previous layer for the next iteration
    previous_layer_nodes = layer_nodes

# Save and view the graph (optional)
dot.render('dfs_transaction_graph', format='png', cleanup=True)
dot.view()

Warning: Orthogonal edges do not currently handle edge labels. Try using xlabels.
Warning: Orthogonal edges do not currently handle edge labels. Try using xlabels.

'dfs_transaction_graph.pdf'

In [92]:
from graphviz import Digraph

# Create a directed graph using Graphviz with hierarchical layout
dot = Digraph()

# Set the graph layout to be hierarchical (left-right) and use L-shaped edges
dot.attr(rankdir='LR', splines='ortho')

# Get the distinct unique layers from the dataset
layers = sorted(df['layer'].unique())

# Initialize the previous layer nodes (starting with an empty set)
previous_layer_nodes = None

# Loop through each distinct layer in the dataset
for layer in layers:
    # Step 1: Retrieve records for the current layer where "Money Transfer" occurs
    layer_records = df[(df['layer'] == layer) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
    layer_nodes = layer_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date', 'ifsc_code', 'amount', 'remarks']]
    
    # Add nodes for the current layer (from_account_no as nodes, with rectangular shape)
    for _, row in layer_nodes.iterrows():
        dot.node(str(row['from_account_no']), label=f"Acc: {row['from_account_no']}\nTransID: {row['transaction_id']}\nIFSC Code: {row['ifsc_code']}\nAmount: {format_amount_indian(row['amount'])}", shape='box')

    # If this is not the first layer, add edges between the previous layer and the current one
    if previous_layer_nodes is not None:
        # Add edges based on "to_account_no" in the current layer matching "from_account_no" in the previous layer
        for _, row in layer_nodes.iterrows():
            matching_previous_layer_nodes = previous_layer_nodes[previous_layer_nodes['from_account_no'] == row['to_account_no']]
            
            for _, prev_row in matching_previous_layer_nodes.iterrows():
                # Add L-shaped edge from the previous layer's from_account_no to the current layer's from_account_no
                dot.edge(str(prev_row['from_account_no']), str(row['from_account_no']), label=f"Transfer on {row['transaction_date']}")

    # Set the current layer as the previous layer for the next iteration
    previous_layer_nodes = layer_nodes

# Save and view the graph (optional)
dot.render('dfs_transaction_graph', format='png', cleanup=True)
dot.view()

Warning: Orthogonal edges do not currently handle edge labels. Try using xlabels.
Warning: Orthogonal edges do not currently handle edge labels. Try using xlabels.

'dfs_transaction_graph.pdf'

In [91]:
from graphviz import Digraph

# Create a directed graph using Graphviz with hierarchical layout
dot = Digraph()

# Set the graph layout to be hierarchical (top-down) and use L-shaped edges
dot.attr(rankdir='LR', splines='ortho')

# Step 1: Retrieve Layer 1 records where "Money Transfer" occurs
layer1_records = df[(df['layer'] == 1) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
layer1_nodes = layer1_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date','ifsc_code', 'amount', 'remarks']]

# Add Layer 1 nodes (from_account_no as nodes, with rectangular shape)
for _, row in layer1_nodes.iterrows():
    dot.node(str(row['from_account_no']), label=f"Acc: {row['from_account_no']}\nTransID: {row['transaction_id']}\nIFSC Code: {row['ifsc_code']}\nAmount: {format_amount_indian(row['amount'])}", shape='box')

# Step 2: Retrieve Layer 2 records where "Money Transfer" occurs
layer2_records = df[(df['layer'] == 2) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
layer2_nodes = layer2_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date','ifsc_code', 'amount', 'remarks']]

# Add Layer 2 nodes and connect edges based on "to_account_no" in Layer 2 matching "from_account_no" in Layer 1
for _, row in layer2_nodes.iterrows():
    # Find matching Layer 1 nodes where to_account_no equals from_account_no in Layer 2
    matching_layer1_nodes = layer1_nodes[layer1_nodes['from_account_no'] == row['to_account_no']]
    
    for _, layer1_row in matching_layer1_nodes.iterrows():
        # Add Layer 2 node with rectangular shape
        dot.node(str(row['from_account_no']), label=f"Acc: {row['from_account_no']}\nTransID: {row['transaction_id']}\nIFSC Code: {row['ifsc_code']}\nAmount: {format_amount_indian(row['amount'])}", shape='box')
        
        # Add L-shaped edge from Layer 1's from_account_no to Layer 2's from_account_no
        dot.edge(str(layer1_row['from_account_no']), str(row['from_account_no']), label=f"Transfer on {row['transaction_date']}\nAmount: {format_amount_indian(row['amount'])}")

# Step 3: Retrieve Layer 3 records where "Money Transfer" occurs
layer3_records = df[(df['layer'] == 3) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
layer3_nodes = layer3_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date','ifsc_code', 'amount', 'remarks']]

# Add Layer 3 nodes and connect edges based on "to_account_no" in Layer 3 matching "from_account_no" in Layer 2
for _, row in layer3_nodes.iterrows():
    # Find matching Layer 2 nodes where to_account_no equals from_account_no in Layer 3
    matching_layer2_nodes = layer2_nodes[layer2_nodes['from_account_no'] == row['to_account_no']]
    
    for _, layer2_row in matching_layer2_nodes.iterrows():
        # Add Layer 3 node with rectangular shape
        dot.node(str(row['from_account_no']), label=f"Acc: {row['from_account_no']}\nTransID: {row['transaction_id']}\nIFSC Code: {row['ifsc_code']}\nAmount: {format_amount_indian(row['amount'])}", shape='box')
        
        # Add L-shaped edge from Layer 2's from_account_no to Layer 3's from_account_no
        dot.edge(str(layer2_row['from_account_no']), str(row['from_account_no']), label=f"Transfer on {row['transaction_date']}\nAmount: {format_amount_indian(row['amount'])}")

# Save and view the graph (optional)
dot.render('dfs_transaction_graph', format='png', cleanup=True)
dot.view()

Warning: Orthogonal edges do not currently handle edge labels. Try using xlabels.
Warning: Orthogonal edges do not currently handle edge labels. Try using xlabels.

'dfs_transaction_graph.pdf'

In [13]:
# Step 1: Retrieve Layer 1 records where "Money Transfer" occurs
layer1_records = df[(df['layer'] == 1) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
layer1_nodes = layer1_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date', 'amount', 'remarks']]

# Create a directed graph
G = nx.DiGraph()

# Add Layer 1 nodes (from_account_no as nodes, with details as attributes)
for _, row in layer1_nodes.iterrows():
    G.add_node(row['from_account_no'], 
               to_account=row['to_account_no'], 
               transaction_id=row['transaction_id'], 
               transaction_date=row['transaction_date'], 
               amount= format_amount_indian(row['amount']), 
               remarks=row['remarks'])

# Step 2: Retrieve Layer 2 records where "Money Transfer" occurs
layer2_records = df[(df['layer'] == 2) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
layer2_nodes = layer2_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date', 'amount', 'remarks']]

# Add Layer 2 nodes and connect edges based on "to_account_no" in Layer 2 matching "from_account_no" in Layer 1
for _, row in layer2_nodes.iterrows():
    # Find matching Layer 1 nodes where to_account_no equals from_account_no in Layer 2
    matching_layer1_nodes = layer1_nodes[layer1_nodes['from_account_no'] == row['to_account_no']]
    
    for _, layer1_row in matching_layer1_nodes.iterrows():
        # Add Layer 2 node
        G.add_node(row['from_account_no'], 
                   to_account=row['to_account_no'], 
                   transaction_id=row['transaction_id'], 
                   transaction_date=row['transaction_date'], 
                   amount= format_amount_indian(row['amount']),
                   remarks=row['remarks'])
        
        # Add edges from Layer 1's from_account_no to Layer 2's from_account_no
        G.add_edge(layer1_row['from_account_no'], row['from_account_no'])

# Step 3: Retrieve Layer 3 records where "Money Transfer" occurs
layer3_records = df[(df['layer'] == 3) & (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
layer3_nodes = layer3_records[['from_account_no', 'to_account_no', 'transaction_id', 'transaction_date', 'amount', 'remarks']]

# Add Layer 3 nodes and connect edges based on "to_account_no" in Layer 3 matching "from_account_no" in Layer 2
for _, row in layer3_nodes.iterrows():
    # Find matching Layer 1 nodes where to_account_no equals from_account_no in Layer 2
    matching_layer2_nodes = layer2_nodes[layer2_nodes['from_account_no'] == row['to_account_no']]
    
    for _, layer2_row in matching_layer2_nodes.iterrows():
        # Add Layer 3 node
        G.add_node(row['from_account_no'], 
                to_account=row['to_account_no'], 
                transaction_id=row['transaction_id'], 
                transaction_date=row['transaction_date'], 
                amount= format_amount_indian(row['amount']),
                remarks=row['remarks'])
        
        # Add edges from Layer 1's from_account_no to Layer 2's from_account_no
        G.add_edge(layer2_row['from_account_no'], row['from_account_no'])

In [15]:
# Create a directed graph
G = nx.DiGraph()

# Iterate over the layers from 1 to 7
for layer in range(1, 8):
    # Retrieve records for the current layer where "Money Transfer" occurs
    layer_records = df[(df['layer'] == layer) & 
                       (df['action_taken_by_bank_wallet_pgpa_merchant_insurance'].str.contains('Money Transfer'))]
    
    # Extract relevant columns
    layer_nodes = layer_records[['from_account_no', 'to_account_no', 'transaction_id', 
                                  'transaction_date', 'amount', 'remarks']]
    
    # Process each record in the current layer
    for _, row in layer_nodes.iterrows():
        # Add the current layer node with 'layer' attribute
        G.add_node(row['from_account_no'], 
                   layer=layer,  # Add 'layer' attribute
                   to_account=row['to_account_no'], 
                   transaction_id=row['transaction_id'], 
                   transaction_date=row['transaction_date'], 
                   amount=format_amount_indian(row['amount']), 
                   remarks=row['remarks'])
        
        # If this is not the first layer, connect edges to the previous layer's nodes
        if layer > 1:
            # Get nodes from the previous layer
            prev_layer_nodes = df[(df['layer'] == layer - 1) & 
                                  (df['to_account_no'] == row['from_account_no'])]
            
            for _, prev_row in prev_layer_nodes.iterrows():
                # Add edge from previous layer's from_account_no to current layer's from_account_no
                G.add_edge(prev_row['from_account_no'], row['from_account_no'])

In [16]:
# Create elements for Dash Cytoscape
cyto_elements = []

# Custom positions to create an L-shape for edges
layer_xs = [100, 300, 600, 900, 1200, 1500, 1800, 2100]  # x-coordinates for each layer
y_increment = 100
current_ys = [100] * 8  # y-coordinates for each layer

# Create a dictionary to store node positions for each layer
layer_node_positions = {}

# Iterate over the layers from 0 to 7
for layer in range(8):
    layer_node_positions[layer] = {}  # Initialize node positions for the current layer
    
    # Iterate over the nodes in the current layer
    for node in G.nodes(data=True):
        if node[1]['layer'] == layer:  # Node belongs to the current layer
            # Define the content string with details in multi-line format
            content = (f"{node[0]}\n"
                       f"To: {node[1]['to_account']}\n"
                       f"Transaction ID: {node[1]['transaction_id']}\n"
                       f"Date: {node[1]['transaction_date']}\n"
                       f"Amount: {node[1]['amount']}\n"
                       f"Remarks: {node[1]['remarks']}")
            
            # Add the node to cyto_elements
            cyto_elements.append({
                'data': {'id': node[0], 'label': content},  # Display node content
                'position': {'x': layer_xs[layer], 'y': current_ys[layer]}  # Positioning for the current layer
            })
            layer_node_positions[layer][node[0]] = (layer_xs[layer], current_ys[layer])  # Track node position for edges
            current_ys[layer] += y_increment  # Increment y-coordinate for the next node in the same layer

# Add edges between nodes in adjacent layers
for edge in G.edges():
    source_layer = next((layer for layer, nodes in enumerate(G.nodes(data=True)) if edge[0] in [node[0] for node in nodes]), None)
    target_layer = next((layer for layer, nodes in enumerate(G.nodes(data=True)) if edge[1] in [node[0] for node in nodes]), None)
    
    if source_layer is not None and target_layer is not None:
        cyto_elements.append({
            'data': {'source': edge[0], 'target': edge[1]},
            'style': {'line-color': '#ff0000', 'width': 2, 'target-arrow-shape': 'triangle', 'arrow-color': '#0074D9'}
        })

In [ ]:

# Create elements for Dash Cytoscape
cyto_elements = []

# Custom positions to create an L-shape for edges
layer1_x = 100
layer2_x = 300  # Shift layer 2 nodes further right
layer3_x = 600
y_increment = 100
current_y = 100

# Add nodes for Layer 1
layer1_node_positions = {}  # Keep track of node positions
for i, node in enumerate(G.nodes(data=True)):
    if node[1]['to_account'] in layer1_nodes['to_account_no'].values:  # Layer 1 nodes
        # Define the content string with details in multi-line format
        content = (f"{node[0]}\n"
                   f"To: {node[1]['to_account']}\n"
                   f"Transaction ID: {node[1]['transaction_id']}\n"
                   f"Date: {node[1]['transaction_date']}\n"
                   f"Amount: {node[1]['amount']}\n"
                   f"Remarks: {node[1]['remarks']}")
         
        cyto_elements.append({
            'data': {'id': node[0], 'label': content},  # Display node content
            'position': {'x': layer1_x, 'y': current_y}  # Positioning for layer 1
        })
        layer1_node_positions[node[0]] = (layer1_x, current_y)  # Track Layer 1 node position for edges
        current_y += y_increment

# Reset y position for Layer 2
current_y = 100

# Add nodes for Layer 2 and edges
layer2_node_positions = {}  # Keep track of layer 2 node positions
for node in G.nodes(data=True):
    if node[1]['to_account'] not in layer1_nodes['to_account_no'].values:  # Layer 2 nodes
        # Define the content string with details in multi-line format
        content = (f"{node[0]}\n"
                   f"To: {node[1]['to_account']}\n"
                   f"Transaction ID: {node[1]['transaction_id']}\n"
                   f"Date: {node[1]['transaction_date']}\n"
                   f"Amount: {node[1]['amount']}\n"
                   f"Remarks: {node[1]['remarks']}")
        
        cyto_elements.append({
            'data': {'id': node[0], 'label': content},  # Display node content
            'position': {'x': layer2_x, 'y': current_y}  # Positioning for layer 2
        })
        layer2_node_positions[node[0]] = (layer2_x, current_y)  # Track Layer 2 node position for edges
        current_y += y_increment

current_y = 100
# Add nodes for Layer 2 and edges
layer3_node_positions = {}  # Keep track of layer 2 node positions
for node in G.nodes(data=True):
    if node[1]['to_account'] not in layer2_nodes['to_account_no'].values:  # Layer 2 nodes
        # Define the content string with details in multi-line format
        content = (f"{node[0]}\n"
                   f"To: {node[1]['to_account']}\n"
                   f"Transaction ID: {node[1]['transaction_id']}\n"
                   f"Date: {node[1]['transaction_date']}\n"
                   f"Amount: {node[1]['amount']}\n"
                   f"Remarks: {node[1]['remarks']}")
        
        cyto_elements.append({
            'data': {'id': node[0], 'label': content},  # Display node content
            'position': {'x': layer3_x, 'y': current_y}  # Positioning for layer 2
        })
        layer3_node_positions[node[0]] = (layer3_x, current_y)  # Track Layer 2 node position for edges
        current_y += y_increment

# Add edges between Layer 1 and Layer 2
for edge in G.edges():
    cyto_elements.append({
        'data': {'source': edge[0], 'target': edge[1]},
        'style': {'line-color': '#ff0000', 'width': 2, 'target-arrow-shape': 'triangle', 'arrow-color': '#0074D9'}
    })

# Initialize Dash app
app = JupyterDash(__name__)

app.layout = html.Div([
    cyto.Cytoscape(
        id='cytoscape-network',
        elements=cyto_elements,
        style={'width': '100%', 'height': '800px'},
        layout={'name': 'breadthfirst'},  # Use preset layout to keep positions defined
        stylesheet=[
            {'selector': 'node', 'style': {'content': 'data(label)', 'shape': 'rectangle', 'background-color': '#00ffD9', 'text-wrap': 'wrap', 'font-size': '12px', 'text-valign': 'bottom', 'text-halign': 'right'}},
            {'selector': 'edge', 'style': {'line-color': '#ff0000', 'curve-style': 'straight', 'target-arrow-shape': 'triangle'}}  # Straight edge styling
        ]
    )
])

if __name__ == '__main__':
    app.run_server(debug=True, port=4282)